language: objective-c
osx_image: xcode9
xcode_project: krugozor-visitorsApp.xcodeproj
xcode_scheme: krugozor-visitorsApp
script:
  - xcodebuild -scheme krugozor-visitorsApp -project krugozor-visitorsApp.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.0' build test
